// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phxgvegpibyjdxsqtdwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoeGd2ZWdwaWJ5amR4c3F0ZHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTg1NzYsImV4cCI6MjA2Nzc3NDU3Nn0.ckmBimMD-UxtVD13zFOccK2_oHZWLiwq-OtpEFGD91Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});