// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phxgvegpibyjdxsqtdwb.supabase.co";
// Legacy JWT anon keys were disabled on this project — use the publishable key
// (same fix as ETPnext: "Fix login: use new Supabase publishable key").
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_VninVHvsBNS6QqwnNdTq3w_u1A_W7tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});